// export const EMAIL_FILLED = 'EMAIL_FILLED'
export const RESET_REQUEST = 'RESET_REQUEST'
export const RESET_SUCCESS = 'RESET_SUCCESS'
export const RESET_FAILED = 'RESET_FAILED'
export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST"
export const SEND_EMAIL_RESPONSE = "SEND_EMAIL_RESPONSE"
export const CLEAR_FORGOT = "CLEAR_FORGOT"
